#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
pip install 'pip <= 24'
# python -m pip install --upgrade pip

# install or upgrade dependencies for development and testing
pip install --no-deps -r ./requirements.lock.txt

# install the package itself in edit mode:
pip install --no-deps -e .

# install pre-commit hooks to git
pre-commit install
